version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
  app:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: ${MSSQL_SA_PASSWORD}